version: "3"

services:
  mongo:
    image: prismagraphql/mongo-single-replica:5.0.3
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "cedric-men"
      MONGO_INITDB_ROOT_PASSWORD: "1521Turtle"
